### ISSUE TITLE
SSD_mobilenet_v1_coco not building under tensorrt 8.* 

### ISSUE THREAD

**Issue by edisanch** [JardinRyu/PedestrianCounter_Jetson#4]
Hi. Trying to build this project for my 4gb model Jetson Nano.
The image comes with tensorrt 8.* , 
When the time comes to build SSD_mobilenet_v1_coco, it fails. 

error seems to be the builder creation in build_engine.py

**Comment by PiotrG1996** [comment]
My error while running ./build_engines.sh

2021-09-05 07:19:57.731985: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.2
WARNING:tensorflow:Deprecation warnings have been disabled. Set TF_ENABLE_DEPRECATION_WARNINGS=1 to re-enable them.
NOTE: UFF has been tested with TensorFlow 1.15.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.9
=== Automatically deduced input nodes ===
[name: "Input"
op: "Placeholder"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 3
      }
      dim {
        size: 300
      }
      dim {
        size: 300
      }
    }
  }
}
]
=========================================

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
WARNING:tensorflow:From /usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py:226: The name tf.AttrValue is deprecated. Please use tf.compat.v1.AttrValue instead.

Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_conf as custom op: FlattenConcat_TRT
Warning: No conversion function registered for layer: GridAnchor_TRT yet.
Converting MultipleGridAnchorGenerator as custom op: GridAnchor_TRT
Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_loc as custom op: FlattenConcat_TRT
DEBUG [/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py:143] Marking ['NMS'] as outputs
No. nodes: 350
UFF Output written to /home/jetson/Jetson_Nano_People_Counting/ssd/ssd_mobilenet_v1_coco.uff
UFF Text Output written to /home/jetson/Jetson_Nano_People_Counting/ssd/ssd_mobilenet_v1_coco.pbtxt
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +203, GPU +0, now: CPU 413, GPU 1930 (MiB)
Traceback (most recent call last):
  File "build_engine.py", line 304, in <module>
    main()
  File "build_engine.py", line 289, in main
    builder.max_workspace_size = 1 << 28
AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'
